Azamat_V: homework_API_Testing_Project_completed
eugene-okulik/Azamat_V pull request #20
Opened 2024-06-27 10:18 UTC by Azamat-V-U

2024-06-28 09:15 UTC, eugene-okulik requested changes
Нужно методы распределить по тем классам, к которым они относятся. Всё остальное хорошо.

2024-06-28 09:15 UTC, eugene-okulik commented on test_api_azamat_v/endpoints/base_endpoint.py
> +        assert self.json["id"] is not None, "The gadget id isn't returned"
Из этих проверок не все подходят для любого ендпоинта. Нужно посмотреть - возможно, какие-то можно перенести в класс того ендпоинта, где они нужны.

2024-06-28 09:15 UTC, eugene-okulik commented on test_api_azamat_v/endpoints/base_endpoint.py
> +        assert self.json["id"] is not None, "The gadget id isn't returned"
А, я понял, ты вообще все проверки сюда вынес. Методы, касающиеся работы с каким-то конкретным ендпоинтом должны находиться в классе того ендпоинта. Например, метод add_new_item_verification явно касается ендпоинта, который добавляет новый гаджет. Вот в тот класс и нужно убрать этот метод, ведь этот метод явно не будет использоваться в тесте удаления и изменения.

2024-06-28 18:54 UTC, Azamat-V-U commented
Перенес методы для проверки тестов в свои классы. Оставил 2 метода для проверки статус кода и имени в классе BaseEndpoint т.к. они могут использоваться как общие для тестов

2024-06-29 08:07 UTC, eugene-okulik commented
> Перенес методы для проверки тестов в свои классы. Оставил 2 метода для проверки статус кода и имени в классе BaseEndpoint т.к. они могут использоваться как общие для тестов

Ага, правильно, в том и суть, что в родительском ендпоинте хранится всё, что нужно всем ендпоинтам (или хотя бы большинству), а остальное уносится в класс того ендпоинта, для которого планируется использоваться.

2024-06-29 08:09 UTC, eugene-okulik approved these changes

2024-06-29 08:09 UTC, merged