Azamat_V: homework_4_completed
eugene-okulik/Azamat_V pull request #3
Opened 2024-05-11 11:42 UTC by Azamat-V-U

2024-05-13 09:58 UTC, eugene-okulik requested changes
Всё отлично, но одну проверочку на внимательность не прошел.

2024-05-13 09:58 UTC, eugene-okulik commented on homework/azamat_valiullin/homework_4/basics_2.py
> +my_dict["dict"]["I am a tuple"] = 6
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-05-14 17:32 UTC, Azamat-V-U reviewed
Done

2024-05-15 05:55 UTC, Azamat-V-U commented on homework/azamat_valiullin/homework_4/basics_2.py
> +my_dict["dict"]["I am a tuple"] = 6
Добавил элемент с ключом ('I am a tupple',  )

2024-05-15 11:25 UTC, eugene-okulik approved these changes

2024-05-15 11:25 UTC, merged