Azamat_V: homework_10_completed
eugene-okulik/Azamat_V pull request #9
Opened 2024-05-27 13:03 UTC by Azamat-V-U

2024-05-28 10:31 UTC, eugene-okulik requested changes
Всё отлично, но последнее задание нужно решить с помощью dict comprehension или с помощью list complrehension. Главное, чтобы в решении был хоть один comprehension, но можно решить и прямо однострочно.

2024-05-28 10:31 UTC, eugene-okulik commented on homework/azamat_valiullin/homework_10/task_2_decorator.py
> +        for i in range(quantity):
Здесь ты создал переменную `i`, которой не пользуешься. Это нормально. Питон иногда какими-то структурами заставляет так делать. В таких ситуациях такие переменные называют `_`  
Было бы
```python
for _ in range(quantity):
```

2024-05-28 10:31 UTC, eugene-okulik commented on homework/azamat_valiullin/homework_10/task_4_list_comprehension.py
> +        words_dictionary[name] = price
Отлично, с помощью цикла решил, а теперь осталось это всунуть в однострочный comprehension. Можно сделать через один comprehension, можно сделать через несколько.

2024-05-28 13:47 UTC, Azamat-V-U commented
Добавил list comprehensions и обьединил в dictionary. Изменил переменную i на _ в цикле for

2024-05-29 10:21 UTC, eugene-okulik approved these changes

2024-05-29 10:21 UTC, merged